### ISSUE TITLE
bug obo -> Spelling Errors DN

### ISSUE THREAD

**Issue by bradrgarrison** [bksubhuti/buddhadust#20]
[Mispellings(edited).docx](https://github.com/bksubhuti/buddhadust/files/3513736/Mispellings.edited.docx)

**Comment by bksubhuti** [comment]
Here are the words from the doc inline
Aappendix
After-deathers
Anthologie
Anthropologie
Arahantship
Arahatship
Bandylegs
Barth
Bathings
Beal
Beruf
Bescorched
Birthstories
Blonay
Bode’s
Broadacres
Buddhaship
Buddhismus
Chalmers’s
Childers’s
Clough
DAVIDS
Davids’s
Dict
Div
Divy
Dup
Eggeling
Eggeling’s
Forn1erly
Fortuitous-Originists
Fourfooted
Gitter
Gliederung
Gliedrung
Glossology
Govinda-ship
Gtary
Harsha
﻿Ka1āra
Kenakid
Kingof
Konow
Lat
Legende
Loc
Lond
Longlived
Minclfulness
Narm
Nature-lorists
Non-Eternalists
Non-eternalists
Norm-body-ness
Normalism
Normalistic
Normness
Ob-serving
One-spake
Ontomasticon
Originists
Palis
Peta-folk
Planudes
Prov
Pyrrhonism
Rebrith
Recht
Recitude
Reconstructors
﻿Religions-geschichtliches
Ritual-literatur
SCETICISM
﻿Sanskritisation
﻿Sanskritised
﻿Sanskritising
﻿Sanskritists
Sarvad
﻿Selfpossessed
﻿Semi-Eternalists
﻿Semi-eternalists
﻿Shakspere
﻿Shakspere's
﻿Shaveling
﻿Shrouder
﻿Signlessness
﻿Studien
﻿Suddas-were
﻿Tad
Thi
Twas
Twere
Ueber
﻿Upanished
Vedic
﻿Vedānta-system
﻿Vedāntist
﻿Vedāntists
﻿Vin.Texts
﻿W'ould
﻿Wahn
﻿Wellfarer
﻿Wellseeing
﻿Werden
﻿Widme
﻿Wonderfu
﻿accom
﻿accuing﻿
﻿addres
﻿afeared
﻿agatn
﻿agreable
﻿al1otted
﻿alsa
﻿alten
﻿alway
﻿amongf
﻿amonor
﻿ance
﻿andswerian
﻿animistically
﻿annexaion
﻿annihilaion
﻿anobject
﻿appeareth
﻿appearsnce
﻿applica
﻿appliction
﻿appre
﻿apprendre
﻿archceological
﻿argumettium
﻿ariseth
﻿asectic
﻿assentingly
﻿atheistical
﻿attainss
﻿b1ows
﻿baed
﻿barmboo
﻿barnfloor
﻿bathings
﻿bathman
﻿bathmen
﻿beareth
﻿becomings
﻿becomng
﻿becumen
﻿befrozen
﻿beginninor
﻿belive
﻿ben
﻿bequeme
﻿besoughtest
﻿bethren
﻿birihs
﻿bond-loosenings
bourne
﻿bronzev﻿
﻿buddhists
﻿buddings
﻿byall
﻿byit﻿
﻿byputting
﻿c1ose
﻿ca1led
﻿calml

﻿cartmakers
﻿causā
﻿cawings﻿
﻿celestials
﻿certainperson
cessant
﻿chank
﻿chank-shell
﻿charnal
﻿chieftin
﻿ciation
﻿cisely
﻿cock's-flightish
﻿cognises
﻿colitions
﻿com
﻿com-motion
﻿come-see-ish
﻿comest
﻿compiete
﻿comprehen
﻿con-fected
﻿con1e
﻿con1prehensive
﻿concensus
﻿concentrxated
﻿condigne
﻿condignus
﻿conditionedness
﻿conformest
﻿connubium
﻿consciousonly
﻿consistantly
﻿conten1plation
﻿convexes
﻿coompany
﻿corectly
﻿cornments
﻿corre
﻿corruscations
﻿cotmplete
﻿courtezan
﻿cowdung
﻿critcal
﻿criven
﻿crosslegged
﻿croucher
﻿croucher-down-on-the-heels
﻿cumbbrous
﻿cupidite
﻿cus
﻿cxercise
﻿dancings
﻿danda
﻿dans
﻿das
﻿deceiftul
﻿deerpark
﻿der
﻿des
﻿desideratives
﻿desolved
﻿devine
﻿dich
﻿difficilior
﻿dificult
﻿digstion
﻿﻿disappearsnce
﻿disentabngle
﻿disolution
﻿distributeth
﻿doggrel
﻿﻿draweth
﻿drivest
﻿droners
﻿dulness
﻿dwasolved
﻿eYil-doer
﻿eachwith
﻿efrort
﻿eiohth
﻿el1e-même
﻿eliminateion
﻿eminating
﻿en1ightened
﻿ence
﻿endeth
﻿enlightemnent
﻿enter's
﻿enteres
﻿entereth
﻿eqivalent
﻿erasion
﻿etc.from
﻿eulalic
﻿ex-pressly
﻿exernal
﻿existence-nonexistence
﻿expianation
﻿explanaion
﻿expungeing
﻿externe
﻿eyne
﻿fac
﻿fait
﻿familias
﻿feo
﻿firma
﻿fisherlad
﻿fixe
﻿foe-subduer
﻿foemen
﻿footborn
﻿footrug
﻿foredone
﻿formere
﻿forthgone
﻿fourfooted
﻿fourty-thousand
﻿fqr
﻿fre
﻿fromits
﻿frotn
﻿﻿fulmen
﻿fundatnental
﻿gael
﻿gainst
﻿gat
﻿ge
﻿gence
﻿gens
﻿gh
﻿﻿givenclue
﻿givings
﻿gnsg
﻿goest
﻿goeth
﻿gottas
﻿governest
﻿governeth
﻿graftings
﻿graspings
﻿greak
﻿gressed
﻿﻿hegins
﻿heither
﻿helpeth
﻿hense
﻿hereness
﻿hied
﻿high-souled
﻿hightest
﻿himon
﻿hoc
﻿hohen
﻿homas
﻿homiuem﻿
﻿houseness
﻿hun1ans
﻿hurricain-like
﻿hypocracy
﻿ihe
﻿illwill
﻿illwill-from
﻿immuable
﻿imporTof
﻿inchastity
﻿incide
﻿incorpreal
﻿inexorabilem
﻿inexorabilis
﻿inflood
﻿influctuate
﻿infonn
﻿ings
﻿inhand
﻿inhérente
﻿inover
﻿inquire's
﻿inscrtptions
﻿insense
﻿instrucing
﻿inteliectual﻿
﻿intelli
﻿intensitive
﻿interestiug
﻿inthe
﻿intinite
﻿jected﻿
﻿ki1esa's
﻿ki1esa-nibbāna
﻿ki1esakama
﻿kinors
﻿knowest
﻿kongey
﻿kora
﻿kusa1ā
﻿leadeth
﻿leafhuts
=﻿long-continned
﻿longlived
﻿longue
﻿lovelv
﻿ma1a-khi1a-ka1i-ki1esa
﻿maintaitied
﻿maketh
﻿mal-aise
﻿malicous
﻿manopolizing
﻿marshalls
﻿mastewhite
﻿mean'st
﻿medita
﻿megas
﻿memonic
﻿memoria
﻿mens
﻿ment
﻿mesure
﻿metempirical
﻿mine-ness
﻿minishèd
﻿mioht
﻿mong
﻿moulh
﻿multipling
﻿multitucle
﻿murch
﻿muring
﻿mū1a-nāma
﻿naro
﻿narrowminded
﻿nats
﻿ness
﻿nicht
﻿nighttime
﻿nineth
﻿ning
﻿nmnber
﻿non-Brahmans
﻿non-Brahmans-clinging
﻿nord
﻿objecive
﻿ofmalevolence
﻿olds
﻿onders
﻿onthe
﻿oo
﻿oposite
﻿orrounds
﻿ot
﻿oul
﻿panied
﻿pany
﻿pasin
﻿pe
﻿perfomed
﻿perfun1es
﻿perous
﻿perserverance
﻿personsworthy
﻿pesons
﻿phant
﻿philodophy
﻿pirit
﻿pleasaunce
﻿poru
﻿posible
﻿powes
﻿pqssessor
﻿principlen
﻿pìs-aller
﻿qave
﻿rccord
﻿rd
﻿re-as-sisted
﻿re-newal
﻿readipgs
﻿recting
﻿rede
﻿redhanded
﻿reflexion
﻿regem
﻿rehgions
﻿religienx
﻿res
﻿revernce
﻿revernce
﻿ri
﻿righteons
﻿rightfu
﻿rightnesses
﻿rik
﻿rinsings
﻿rn
﻿ronde
﻿rrepeated
﻿rutum
﻿scarers
﻿scil
﻿se
﻿selfcontrol
﻿seve
﻿shih
﻿should'st
﻿sht
﻿si
﻿sion
﻿sive
﻿skelleton
﻿﻿smar
﻿smne
﻿smon
﻿somethng
﻿somewhats
﻿soverign
﻿spahte
﻿spakc﻿
﻿﻿spile
﻿spirituallyminded
﻿sponding
﻿st
﻿standi
﻿stedfast
﻿sthought
﻿stor
﻿strean
﻿strem
﻿su1addhaɱ
﻿supersitions
﻿sur
﻿sustined
﻿svar
﻿swerian
﻿syena
﻿synovic
﻿tbe
﻿tenn
﻿th
﻿th'Enlightened
﻿th'admonished
﻿th'enlightened
﻿th'enshrouding
﻿tha
﻿thau
﻿theBuddha
﻿then1selves
﻿therethen
﻿therin
﻿these-Khattiyas
﻿thesun
﻿they.And
﻿thhere
﻿thingis
﻿thinigs
﻿tion
﻿tlie
﻿tman
﻿tnan
tnay
﻿tnrough
﻿toand
﻿toany
﻿togain
﻿tokeep
﻿tolook
﻿tomastery
﻿torapt
﻿torule
﻿trangress
﻿transl
﻿trate
﻿ts
﻿twice-twayfooted
﻿twofooted
﻿ultra-thoughtish
﻿un-Aiyan 
﻿un-Ariyan 
﻿unabridge  
﻿unble1nished  ﻿ 
﻿und  
﻿une  
﻿unskakeable 
﻿unsseasonable 
﻿unsurpassables 
﻿untranslateable ﻿  
﻿vaine
﻿vanous
﻿veneerable
﻿vener
﻿venerableĀnanda
﻿ver
﻿vero
﻿versatum
﻿vient
﻿viewy
﻿vo
﻿voce
﻿vorthy
﻿vraisemblance
﻿vs
﻿vthat
﻿w
﻿watchover
﻿weil
﻿weorthan
﻿whenhe
﻿whocombined
﻿whoe'er
﻿whosoe'er
﻿wight
﻿wiil
﻿wili
﻿withhis
﻿withinsight 
﻿withneither
﻿withopen
﻿withthe
﻿withvirtues
﻿wlsh
﻿wn
﻿worIdly
﻿worthicst
﻿worthx
﻿writh
﻿wrorld
﻿ ﻿ws
﻿yan
﻿yaries
﻿yonger
﻿youred
﻿zu	
﻿zuait
