### ISSUE TITLE
an TOC

### ISSUE THREAD

**Issue by bksubhuti** [bksubhuti/buddhadust#23]
The TOC has only the sutta number.. if it is possible to have the book chapter and sutta that would be more manageable .  I think I see the possibility of this happening

Sample TOC
(level 1) VIII. The Book of the Eights
(level 2)        I. On Amity
(level 3)               Sutta 4

**Comment by bksubhuti** [comment]
For Wisdom pubs.. the html page for each book may not be necessary.
First there is the book
Then chapter
The sutta number.


It seems that the sutta number should be consecutive for each book starting at zero.  The chapters continue the number... It looks like this might be possible now that we have plugin power.. 
We can generate a TOC by HTML and then delete duplicate instances after the first instance is found.
This will give a proper nested TOC.  

mock code would be...
assuming we have   book as h1 chapter has h2 and sutta as h3  (we can also do that in code too)

- book1
-     cha1
-        sutta1
- book1
-     cha1
-        sutta2
- book1
-     cha1
-        sutta3
- book1
-     cha1
-        sutta4
- book1
-     cha1
-        sutta5
- book2
-     cha1
-        sutta1
- book2
-     cha1
-        sutta2
- book2
-     cha2
-        sutta3
- book2
-     cha2
-        sutta4
- 

We can search for 'The Book of'
```
strBookOf=""
strChapter=""

# assuming that re.sub returns NULL if search string is not found.

While (strLine=Readline (tocfile)<> EOF)
{
     strRegEx = re.sub"The Book of -----", using strLine)  #find a book title (if any on that line)
     if (strRegEx)
          strBookOf = strRegEx
     if ( strBookOf == strBookof)  #if it is the first instance of that book title then do not delete
           delete strBookOf from strLine  #if it is duplicate.. delete it
      
      strRegEx = re.sub("Chapter ---")  #find a chapter if any...
          if (strRegEx)
                strChapter  = strRegEx 
          if (strChapter  == strChapter) #if it is first instance of that chapter #and text, keep it
               delete strChapter from strLine  #if it is duplicate delete it
      Writeline (newfile)
}

Will something like this be easy to write?
It has been a long time since I wrote any real code and I am embarrassed... too..

**Comment by CaptainValor** [comment]
As for including the Sutta number ranges for Books 3-11, we need to decide how to do this (since obo doesn't include such pre-generated ranges as headers in the pages, as with Books 1 and 2). How about something like...

* `III. The Book of the Threes`
* `   I. The Fool | 1-10`
* `   II. The Wheelwright | 11-20`
* `   II. On Persons | 21-30`

or

* `III. The Book of the Threes`
* `   I. The Fool | Suttas 1-10`
* `   II. The Wheelwright | Suttas 11-20`
* `   II. On Persons | Suttas 21-30`

?

**Comment by CaptainValor** [comment]
Exceptions to the pattern...

* AN V.XXVI has sub-pages with ranges as well, since it contains 946 suttas, so those can included beneath it in the TOC
* (will add more exceptions here as I find them)

**Comment by CaptainValor** [comment]
TOC draft of AN in this style is complete. Check it out... [ePub](https://github.com/bksubhuti/buddhadust/blob/master/pts-ebooks/an/an-toc-fork/an-epub-toc-fork.epub) | [XML](https://github.com/bksubhuti/buddhadust/blob/master/pts-ebooks/an/src/v0.3/Text/TOC.xhtml)

**Comment by bksubhuti** [comment]
Looks great!  Closed
