### ISSUE TITLE
spellcheck method?

### ISSUE THREAD

**Issue by bksubhuti** [bksubhuti/buddhadust#26]
How should we spellcheck when we fork off? Should we do it individually to each epub?  or should we use a grep tool for the htm files?

My idea is that if we use a grep search and replace, we can fix the misspellings from one nikaya to the other nikayas.  Therefore , as we spellcheck each nikaya it will be less and less.

One the other hand, we need to make a list (which we have), as we do it and then split the tools.
sigil will let us edit directly and bring us directly to the word and we can replace all there.

Which is best?

**Comment by CaptainValor** [comment]
Let's discuss this in a video chat today. I agree with using Grep on the HTMs all at once. I imagine we could write a BASH script that imports a table of spelling corrections and search/replaces each of them for each file in a given directory. We could then re-import those corrected HTMs into Sigil.

**Comment by bksubhuti** [comment]
added ods will refine

**Comment by bksubhuti** [comment]
Csv is with only with wrong words.  Will add corrected words.  The spellings should have a space at the end because they are words and sometimes they may be part of other words.  To resolve this we should search for space at the end.
Can we get an output script to find the words that still exist in the list?  Similar script.

Should we make one for MN and AN and DN etc or should it be global?  Maybe global is better?

**Comment by CaptainValor** [comment]
Figured out a method that just uses two files and a *single terminal command*. [Check it out](https://github.com/bksubhuti/buddhadust/blob/master/pts-ebooks/mn/spelling-correction/script/README.md)
