### ISSUE TITLE
T is not Bold on Thus I have heard

### ISSUE THREAD

**Issue by bksubhuti** [bksubhuti/buddhadust#3]
The T is not bold on thus I have heard

looks like T**HUS**

![image](https://user-images.githubusercontent.com/18184280/62828669-c5802700-bb87-11e9-9fd6-bc90cfd828cb.png)

**Comment by CaptainValor** [comment]
Resolved in latest Beta.

**Comment by bksubhuti** [comment]
Still problems on latest pull 4:10 pm both mobi and epub using Calibre ebook viewer app.

**Comment by CaptainValor** [comment]
Which Sutta?

**Comment by bksubhuti** [comment]
I spot checked first three suttas using caliber ebook.  Microsoft edge is the same.

**Comment by CaptainValor** [comment]
You might need to do another Fetch Origin. They look correct in Calibre on my end.
