### ISSUE TITLE
Approve Credits Page

### ISSUE THREAD

**Issue by CaptainValor** [bksubhuti/buddhadust#30]
@bksubhuti How does this feel?

- - -

<h1>Credits</h1>
<br/>
<p>Transcribed, Unabridged, and Annotated by</p>
<b>Michael M. Olds</b>
<br/><br/>
<p>Edited for eBook Release by</p>
<b>Bhante Bhikkhu Subhuti</b>
<br/>
<b>Stephen J. Torrence</b>

**Comment by bksubhuti** [comment]
Obo would be preferred even though his real name is listed in some places.  Obo is listed in other places and since he does not want to be listed in github we can assume the same in the epub
Or “Obo, the  admin of Buddhadust.net”
Something like that

**Comment by CaptainValor** [comment]
Done. Added to credits file in latest commit.
