### ISSUE TITLE
obo ->  Change spelling of "ṅ" and  "ṃ"

### ISSUE THREAD

**Issue by bksubhuti** [bksubhuti/buddhadust#6]
Request to change the spelling of pali words to match the international Unicode standards.

It is also important if someone uses a font conversion too from one country's script (Myanmar or Thai Script) to the next from your website..

Example.. 
cūḷataṇhāsaṅkhayasuttaṃ (MN 37)
Cūḷa Taṇhā Saŋkhaya Suttaɱ

**Comment by CaptainValor** [comment]
Provisionally doing this through Find/Replace in the eBook version. Assuming you mean this to refer to the Buddhadust HTML versions?

**Comment by bksubhuti** [comment]
We will do this internally and with dot of m on top
